ukui/kylin-nm

kylin-nm.pro, src/mainwindow.cpp, src/mainwindow.h, src/mainwindow.ui, src/switchbutton.cpp, src/switchbutton.h
=> Change the SwitchButton's style

src/main.cpp
* 取消分辨率判断，解决Qt5.6版本上4K更改分辨率后缩放不正确问题
=> Fix: Remove resolution judgment

src/ksimplenm.cpp, src/mainwindow.cpp
Description: 修复每次刷新WIFI列表会把所有WIFI添加一次的问题
=> fix(wpa-wifi): All wifis will be added to wifi list everytime it refreshed.

src/backthread.cpp, src/mainwindow.cpp, src/mainwindow.h
=> feat(mainwindow): Optimize code logic.

src/oneconnform.cpp, src/wpawifidialog.cpp, src/wpawifidialog.h
Description: 修复实例化WIFI名称不对的bug，添加每次询问密码的选项
Log: 修复实例化WIFI名称不对的bug，添加每次询问密码的选项
=> feat(wpa wifi): Add askPwd checkbox and fix incorrect wifi name.

src/mainwindow.cpp
Description: 修复wifi频率图标显示不准确的问题
=> fix(wifi-freq): Wifi freq label is not accurate

src/mainwindow.h, src/oneconnform.cpp, src/wpawifidialog.cpp, wireless-security/dlghidewifi.cpp
Description: 修改添加隐藏企业wifi的弹窗为与连接企业wifi弹窗一致
=> feat(wpa-wifi): Add hidden wpa wifi.

src/wpawifidialog.cpp, wireless-security/dlghidewifiwpa.cpp
Description: 修复点击加入个人wifi后点击企业Wifi弹窗有误的问题
修改连接企业wifi的超时时间以保证有足够的时间验证密码
=> fix(add-wifi): Dialog is incorrect when choose wpa-wifi after chosen wep-wifi.

src/oneconnform.cpp, src/wpawifidialog.cpp
=> feat(Freq label): Adjust ui style.

src/backthread.cpp, src/mainwindow.cpp, src/wpawifidialog.cpp
Description: 修复网卡配置中刷新网络列表导致wifi列表显示错误的问题
=> fix(Wifi): Wifilist display incorrectly.

src/ksimplenm.cpp, src/ksimplenm.h, src/kylin-dbus-interface.cpp, src/kylin-dbus-interface.h, src/mainwindow.cpp, src/mainwindow.h
Log: 修复新添加的wifi不会自动连接的Bug
Bug: http://172.17.66.192/biz/bug-view-31134.html
=> fix(wifi): Added wifi will not be connected automatically.

src/mainwindow.cpp, src/oneconnform.cpp
Description: 修复新增wifi连接失败的问题
问题原因：检测到新增wifi会自动尝试连接，此时未加状态值判断，导致手动点击连接和自动连接冲突
=> fix(wifi): New wifi connected failed.

src/mainwindow.cpp, src/oneconnform.cpp, src/oneconnform.h, src/wpawifidialog.cpp, src/wpawifidialog.h
Log: 修复wifi安全性变更后无法正常连接的bug
Bug: http://172.17.66.192/biz/bug-view-34664.html
Log: 修复新wifi会被添加到列表底部的问题
Bug: http://172.17.66.192/biz/bug-view-31073.html
=> fix(wifi): Wifi can not be connected which security is changed to be psk from eap.

src/backthread.cpp, src/confform.cpp, src/confform.h, src/oneconnform.cpp, src/onelancform.cpp
Log: 修复设置ipv6地址失败的Bug
Bug: http://172.17.66.192/biz/bug-view-38287.html
=> fix(confform): Set ipv6.address failed.

src/backthread.cpp, src/backthread.h, src/kylin-dbus-interface.cpp, src/kylin-dbus-interface.h, src/kylin-network-interface.c, src/mainwindow.cpp, src/mainwindow.h, src/oneconnform.cpp
Log: 修复设置ipv4地址后wifi不会自动重连的bug
Bug: http://172.17.66.192/biz/bug-view-36571.html
=> fix(wifi): Wifi is not reconnected after setting ipv4.address

src/kylin-dbus-interface.cpp, src/mainwindow.cpp, src/mainwindow.h
Description: 修复连接wifi时wifi开关被关闭的问题
Log: 修复连接wifi时wifi开关被关闭的问题
=> fix(wifi): wifi button is closed when connected wifi.

src/confform.cpp, src/mainwindow.cpp, src/oneconnform.cpp
取消字符转义，通过单(util)、双(qprocess)引号分隔网络名称参数来避免传值错误的问题
=> Optimize code.

src/confform.cpp, src/confform.ui, src/mainwindow.h
修复字体过大时部分文字显示不全的bug
Link: http://172.17.66.192/biz/bug-view-43978.html
=> Fix: Some labels can not be completely displayed in large font-size.

src/mainwindow.cpp
=> remove frequency qlabel when switch off wifi

src/mainwindow.cpp
FIX : 修改WiFi刷新后会出现相同的列表问题
LINK:#44159
=> 本次和上次的表头信息中，path的开始位置不一定一样；使用相应的path位置

src/kylin-dbus-interface.cpp
FIX：解决  连接IPV6后kylin-nm出现段错误的问题；
LINK：BUG #49061
=> 解决几处Qlist使用不规范可能导致段错误的问题

src/confform.cpp, src/confform.h, src/kylin-network-interface.c, src/kylin-network-interface.h, src/onelancform.cpp
Log: 修复仅配置ipv6地址时无法保存的问题
Bug: http://172.17.66.192/biz/bug-view-49079.html
=> fix(configuration): It's not permitted to save configuration when only set ipv6 address.

src/mainwindow.cpp, src/mainwindow.h
=> Fix:Wifi choosen is incorrect.

src/mainwindow.cpp, src/mainwindow.h
=> Fix: Refresh wifi failed when it is in lan list.

src/dbusadaptor.h, src/mainwindow.cpp, src/mainwindow.h, src/oneconnform.cpp
为修改ip后控制面板未同步的问题提供接口
http://172.17.66.192/biz/bug-view-54353.html
修复WiFi密码改变后重新连接失败且不允许输入密码的问题。
修复WiFi自动连接和断开后WiFi列表状态未更新的问题
Link：http://172.17.66.192/biz/bug-view-53041.html
=> Fix: Wifi infomation is not sync with ukui-control-center.

src/ksimplenm.cpp, src/mainwindow.cpp
修复已连接wifi对应bssid频率标签错误的bug
Link: http://172.17.66.192/biz/bug-view-50611.html
修复ssid含中文的WiFi更新时会被误添加的bug(调整了属性的获取顺序来保证列对齐）
=> Fix:Frequence Label for connected wifi is incorrect.

src/ksimplenm.cpp, src/ksimplenm.h, src/mainwindow.cpp, src/mainwindow.h, src/oneconnform.cpp
代码优化，回连失败时不再删除配置文件，会按优选列表顺序依次尝试重连直到连接成功，且回连开始与结束时会发信号通知列表中的wifi更新loading状态
=> Optimize code for wifi reconnection.

src/backthread.cpp, src/mainwindow.cpp
优化回连失败算法，若有多个同名AP均被选入回连列表，当其中一个回连失败，后续的将不再尝试
修复没有有线网卡的设备点击有线网时kylin-nm崩溃的问题
修复v10sp1获取不到wifi列表的问题
=> Optimze code.

src/backthread.cpp, src/main.cpp, src/mainwindow.cpp, src/oneconnform.cpp, src/wpawifidialog.cpp
Description: 添加日志文件，可通过tail -f .config/ukui/kylin-nm.log查看
=> feat(log): Add log file.

src/dbusadaptor.h, src/kylin-dbus-interface.cpp, src/kylin-dbus-interface.h, src/mainwindow.cpp, src/mainwindow.h
Description: 当有线网增删连断时，发出dbus信号通知控制面板更新
=> feat(lan): Emit dbus signal when lan connected/disconnected/added/removed

src/backthread.cpp, src/backthread.h, src/oneconnform.cpp, src/oneconnform.h
=> fix(wifi): WPA3 can not be connected successfully.

src/wpawifidialog.cpp, wireless-security/dlghidewifi.cpp, wireless-security/dlghidewifieapfast.cpp, wireless-security/dlghidewifieapleap.cpp, wireless-security/dlghidewifieappeap.cpp, wireless-security/dlghidewifieappwd.cpp, wireless-security/dlghidewifieaptls.cpp, wireless-security/dlghidewifieapttls.cpp, wireless-security/dlghidewifileap.cpp, wireless-security/dlghidewifiwep.cpp, wireless-security/dlghidewifiwpa.cpp, wireless-security/kylinheadfile.cpp, wireless-security/kylinheadfile.h
Description: 修复透明度高时按钮样式突兀的问题
Log: 修复透明度高时按钮样式突兀的问题
Bug: http://pm.kylin.com/biz/bug-view-31245.html
=> fix(ui): Style of button is abrupt in high transparecy.

src/mainwindow.cpp
Description: 修复已连接的热点关闭时前端显示错误的问题
=> fix(wifi): Top item is empty when connected ap disappeared,
